server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://139.196.6.43:3306/hospital

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ythyth
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hospital.entity
  http:
    multipart:
      maxFileSize: 500Mb
      maxRequestSize: 500Mb
filepath:
  appointpdf: ./
  seekpdfpath: ./

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO

reggie:
  path: \